force-app/main/default/objects/Case/fields/Component__c.field-meta.xml
<CustomField>
    <fullName>Component__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Component</label>
    <referenceTo>Component__c</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Component__c/Component__c.object-meta.xml
<CustomObject>
    <description>Lippert products within an RV</description>
    <label>Component</label>
    <nameField>
        <label>Component Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Components</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Component__c/fields/ProductUniqueId__c.field-meta.xml
<CustomField>
    <fullName>ProductUniqueId__c</fullName>
    <externalId>true</externalId>
    <label>ProductUniqueId</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Component__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Not Connected</fullName>
            </value>
            <value>
                <fullName>Normal</fullName>
            </value>
            <value>
                <fullName>Error</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/LippertComponentCode__e/LippertComponentCode__e.object-meta.xml
<CustomObject>
    <label>LippertComponentCode</label>
    <pluralLabel>LippertComponentCodes</pluralLabel>
</CustomObject>

force-app/main/default/objects/LippertComponentCode__e/fields/DTC_Type__c.field-meta.xml
<CustomField>
    <fullName>DTC_Type__c</fullName>
    <label>DTC Type</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/LippertComponentCode__e/fields/ProductUniqueID__c.field-meta.xml
<CustomField>
    <fullName>ProductUniqueID__c</fullName>
    <label>ProductUniqueID</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/demoToolsCtrl.cls
public with sharing class demoToolsCtrl {


    @AuraEnabled
    public static void fullReset(){

        //set all the components back to "Normal"
        list<Component__c> Components = [select id, status__c from Component__c];
        for(Component__c c:components){
            c.Status__c = 'Normal';
        }
        update Components;

        //delete any cases
        delete [select id from Case];

        //delete all chatter
        delete [select id from FeedItem];
    }

    @AuraEnabled
    public static void allComponentsSendOK(){
        list<Component__c> Components = [select id, ProductUniqueId__c from Component__c];
        list<LippertComponentCode__e> events = new list<LippertComponentCode__e>();
        for(Component__c c:components){
            LippertComponentCode__e e = new LippertComponentCode__e();
            e.ProductUniqueId__c = c.ProductUniqueId__c;
            e.DTC_Type__c = 'OK';
            events.add(e);
        }

        Eventbus.publish(events);
    }
}